CREATE DATABASE SHOPMANAGERS
GO
USE SHOPMANAGERS
GO 
-- FOOD 
-- TABLE
-- FOODCATEGORY
-- ACCOUNT
-- BILL
-- BILLINFO

CREATE TABLE TABLEFOOD(
ID INT IDENTITY PRIMARY KEY ,
NAME NVARCHAR(100) NOT NULL DEFAULT N'BAN CHUA CO TEN',
STATUS NVARCHAR(100) NOT NULL DEFAULT N'NO'
)
GO

CREATE TABLE ACCOUNT(
USERNAME NVARCHAR(100) PRIMARY KEY,
DISPLAYNAME NVARCHAR(100) NOT NULL DEFAULT N'THANH SANG',
PASSWORD NVARCHAR(1000) NOT NULL DEFAULT 0,
TYPE INT NOT NULL DEFAULT 0
)
GO

CREATE TABLE FOODCATEGORY(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(100)  NOT NULL DEFAULT N'CHUA DAT TEN'
)
GO

CREATE TABLE FOOD(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR (100) NOT NULL DEFAULT N'CHUA DAT TEN',
IDCATEGORY INT NOT NULL,
PRICE FLOAT NOT NULL DEFAULT 0
FOREIGN KEY (IDCATEGORY) REFERENCES DBO.FOODCATEGORY(ID)
)
GO

CREATE TABLE BILL(
ID INT IDENTITY PRIMARY KEY ,
DATECHECKIN DATE NOT NULL DEFAULT GETDATE(),
DATECHECKOUT DATE,
IDTABLE INT NOT NULL,
DISCOUNT INT,
TOTALPRICE DECIMAL,
STATUS INT NOT NULL DEFAULT 0
FOREIGN KEY (IDTABLE) REFERENCES DBO.TABLEFOOD(ID)
)
GO

CREATE TABLE BILLINFO(
ID INT IDENTITY PRIMARY KEY ,
IDBILL INT NOT NULL,
IDFOOD INT NOT NULL,
COUNT INT NOT NULL DEFAULT 0
FOREIGN KEY (IDBILL) REFERENCES DBO.BILL(ID),
FOREIGN KEY (IDFOOD) REFERENCES DBO.FOOD(ID)
)
GO

INSERT INTO DBO.ACCOUNT(
USERNAME,
DISPLAYNAME,
PASSWORD,
TYPE
)
VALUES(
N'THANHSANG',
N'HOMAITHANHSANG',
N'1',
1
)

INSERT INTO DBO.ACCOUNT(
USERNAME,
DISPLAYNAME,
PASSWORD,
TYPE
)
VALUES(
N'THANHSANG1',
N'HOMAITHANHSANG1',
N'12',
0
)
GO

CREATE PROC USP_GETACCOUNTUSERNAME
DECLARE @USERNAME NVARCHAR(100)
AS
BEGIN
SELECT * FROM DBO.ACCOUNT WHERE USERNAME = @USERNAME
END
GO

EXEC DBO.USP_GETACCOUNTUSERNAME @USERNAME = N'THANHSANG'




SELECT *FROM DBO.ACCOUNT WHERE USERNAME = N'THANHSANG'

SELECT *FROM DBO.ACCOUNT WHERE USERNAME = N' ' AND PASSWORD = N''OR	1 = 1--'

SELECT *FROM DBO.ACCOUNT WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD



---------------TÀI TIẾP TỤC CODE

--THÊM BÀN
DECLARE @i INT = 0;
WHILE @i <= 20
BEGIN
    INSERT INTO dbo.TABLEFOOD (name, STATUS) VALUES (N'Bàn ' + CAST(@i AS nvarchar(100)), N'Trống');
    SET @i = @i + 1;
END
GO


CREATE PROC USP_GetTableList
AS SELECT * FROM dbo.TABLEFOOD
GO

UPDATE dbo.TABLEFOOD SET STATUS = N'Có người' WHERE id = 9

EXEC dbo.USP_GetTableList


--THÊM CATEGORY
INSERT dbo.FOODCATEGORY (NAME) VALUES (N'Hải sản')
INSERT dbo.FOODCATEGORY (NAME) VALUES (N'Nông sản')
INSERT dbo.FOODCATEGORY (NAME) VALUES (N'Lâm sản')
INSERT dbo.FOODCATEGORY (NAME) VALUES (N'Sản sản')
INSERT dbo.FOODCATEGORY (NAME) VALUES (N'Nước')
GO

--THÊM MÓN ĂN
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Mực một nắng nước sa tế', 1, 120000)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Nghêu hấp xả', 1, 50000)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Dú dê nướng sữa', 2, 60000)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Heo rừng nướng muối ớt', 3, 75000)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Cơm chiên mushi', 4, 999999)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'7Up', 5, 15000)
INSERT dbo.FOOD (NAME,IDCATEGORY,PRICE) VALUES (N'Cafe', 5, 12000)
GO

----THÊM BILL
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 1 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 2 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 3 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 4 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 5 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 6 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 7 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 8 , 0, 0 )
--INSERT dbo.BILL (DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS,DISCOUNT) VALUES (GETDATE(), NULL, 9 , 0, 0 )
--GO


----THÊM BILLINFO
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 1, 6, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 1, 5, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 2, 5, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 2, 3, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 3, 1, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 3, 2, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 4, 3, 4)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 4, 2, 4)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 5, 5, 1)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 5, 6, 1)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 6, 1, 2)
--INSERT dbo.BILLINFO (IDBILL,IDFOOD,COUNT) VALUES ( 7, 6, 2)
--GO

ALTER PROC USP_InsertBill
@idTable INT
AS
BEGIN
	INSERT dbo.Bill (DateCheckIn, DateCheckOut , idTable, status)
	VALUES  ( GETDATE() ,NULL , @idTable , 0)
END
GO

ALTER PROC USP_InsertBillInfo
@idBill INT, @idFood INT, @count INT
AS
BEGIN

	DECLARE @isExitsBillInfo INT
	DECLARE @foodCount INT = 1
	
	SELECT @isExitsBillInfo = id, @foodCount = b.count 
	FROM dbo.BillInfo AS b 
	WHERE idBill = @idBill AND idFood = @idFood

	IF (@isExitsBillInfo > 0)
	BEGIN
		DECLARE @newCount INT = @foodCount + @count
		IF (@newCount > 0)
			UPDATE dbo.BillInfo	SET count = @foodCount + @count WHERE idFood = @idFood
		ELSE
			DELETE dbo.BillInfo WHERE idBill = @idBill AND idFood = @idFood
	END
	ELSE
	BEGIN
		INSERT	dbo.BillInfo
        ( idBill, idFood, count )
		VALUES  ( @idBill, -- idBill - int
          @idFood, -- idFood - int
          @count  -- count - int
          )
	END
END
GO


ALTER TRIGGER UTG_UpdateBillInfo
ON dbo.BillInfo FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @idBill INT
	
	SELECT @idBill = idBill FROM Inserted
	
	DECLARE @idTable INT
	
	SELECT @idTable = idTable FROM dbo.Bill WHERE id = @idBill AND status = 0
	
	UPDATE dbo.TableFood SET status = N'Có người' WHERE id = @idTable
END
GO

ALTER TRIGGER UTG_UpdateBill
ON dbo.Bill FOR UPDATE
AS
BEGIN
	DECLARE @idBill INT
	
	SELECT @idBill = id FROM Inserted	
	
	DECLARE @idTable INT
	
	SELECT @idTable = idTable FROM dbo.Bill WHERE id = @idBill
	
	DECLARE @count int = 0
	
	SELECT @count = COUNT(*) FROM dbo.Bill WHERE idTable = @idTable AND status = 0
	
	IF (@count = 0)
		UPDATE dbo.TableFood SET status = N'Trống' WHERE id = @idTable
END
GO

----BAI 13
CREATE PROC USP_SwitchTable
@idTable1 int, @idTable2 int
AS BEGIN

	DECLARE @idFirstBill INT
	DECLARE @idSecondBill INT

	SELECT @idSecondBill = id FROM dbo.BILL WHERE IDTABLE = @idTable2 AND STATUS = 0
	SELECT @idFirstBill = id FROM dbo.BILL WHERE IDTABLE = @idTable1 AND STATUS = 0

	IF(@idFirstBill = null)
	BEGIN
		INSERT dbo.BILL(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS) VALUES (GETDATE(),NULL,@idTable1,0)
		SELECT @idFirstBill = MAX(id) FROM dbo.BILL WHERE IDTABLE = @idTable1 AND STATUS = 0
	END

	IF(@idSecondBill = null)
	BEGIN
		INSERT dbo.BILL(DATECHECKIN,DATECHECKOUT,IDTABLE,STATUS) VALUES (GETDATE(),NULL,@idTable2,0)
		SELECT @idSecondBill = MAX(id) FROM dbo.BILL WHERE IDTABLE = @idTable2 AND STATUS = 0
	END



	SELECT id INTO IDBillInfoTable FROM dbo.BILLINFO WHERE IDBILL = @idSecondBill

	UPDATE dbo.BILLINFO SET IDBILL = @idSecondBill WHERE IDBILL = @idFirstBill

	UPDATE dbo.BILLINFO SET IDBILL = @idFirstBill WHERE id IN(SELECT * FROM IDBillInfoTable)

	DROP TABLE IDBillInfoTable







DELETE dbo.BILLINFO
DELETE dbo.BILL



delete dbo.TABLEFOOD
delete DBO.BILL
delete DBO.BILLINFO

SELECT * FROM dbo.TABLEFOOD
SELECT * FROM dbo.BILL
SELECT * FROM dbo.BILLINFO
SELECT * FROM dbo.FOOD
SELECT * FROM dbo.FOODCATEGORY

UPDATE dbo.Bill SET dateCheckOut = GETDATE(), status = 1, discount = 0, totalPrice = 0 WHERE id = 1
